### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by JamesKegel** [gilchenzion/learnyouredux#1]
npm install -g learnyouredux -g 

npm ERR! code E404
npm ERR! 404 Not Found: learnyouredux@latest

**Comment by gilchenzion** [comment]
Hey @JamesKegel this repo was a complete work in progress and is nowhere near helpful. I'm going to remove it so it doesn't cause issues for anyone else. I will say, the egghead tutorial is a good place to check out https://egghead.io/courses/getting-started-with-redux

**Comment by JamesKegel** [comment]
Thanks, that's what I'm currently working through. 

Take care
